version: "3.8"

services:
  # scraper-api:
  #   build:
  #     context: .
  #     dockerfile: docker/app/Dockerfile
  #   container_name: scraper-api
  #   restart: always
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   command: >
  #     sh -c "cd src && \
  #            uvicorn main:app --host 0.0.0.0 --port ${API_PORT} --reload --loop asyncio"
  #   volumes:
  #     - .:/app
  #   networks:
  #     - scraper-network
  #   env_file:
  #     - .env
  #   dns:
  #     - 8.8.8.8

  preload-browsers:
    image: docker:latest
    command: >
      sh -c "
      docker pull selenoid/firefox:115.0 &&
      exit 0
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  scraper-selenoid:
    image: aerokube/selenoid:latest-release
    container_name: scraper-selenoid
    privileged: true
    restart: always
    command: [
        "-conf",
        "/etc/selenoid/browsers.json",
        # "-container-network",
        # "selenoidtest_scraper-network",
        "-timeout",
        "1m30s",
      ]
    # expose:
    #   - 4444
    ports:
      - 4444:4444
    volumes:
      - D:/PYTHON/Projects/SelenoidTest/docker/selenoid/browsers.json:/etc/selenoid/browsers.json
      - /var/run/docker.sock:/var/run/docker.sock
    # networks:
    #   - scraper-network
# networks:
#   scraper-network:
#     driver: bridge
